import type {
  Tournament,
  Player,
  Court,
  Role,
  Match,
  ActivityItem,
  UpcomingMatch,
} from "@/types";

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: "1",
    organizationId: "org1",
    name: "Sunday League #8",
    sport: "Badminton",
    sportIcon: "🏸",
    date: "2025-05-25",
    venueId: "v1",
    venueName: "Cebu Sports Complex",
    format: "single_elimination",
    status: "live",
    progress: 67,
    divisionCount: 3,
    playerCount: 32,
    createdAt: "",
  },
  {
    id: "2",
    organizationId: "org1",
    name: "Cebu Open 2025",
    sport: "Badminton",
    sportIcon: "🏸",
    date: "2025-06-08",
    venueId: "v2",
    venueName: "SM Seaside Gym",
    format: "single_elimination",
    status: "upcoming",
    progress: 40,
    divisionCount: 5,
    playerCount: 64,
    createdAt: "",
  },
  {
    id: "3",
    organizationId: "org1",
    name: "IT Park Smashers",
    sport: "Table Tennis",
    sportIcon: "🏓",
    date: "2025-06-15",
    venueId: "v3",
    venueName: "IT Park Activity Center",
    format: "round_robin",
    status: "open",
    progress: 0,
    divisionCount: 2,
    playerCount: 16,
    createdAt: "",
  },
  {
    id: "4",
    organizationId: "org1",
    name: "Sunday League #7",
    sport: "Badminton",
    sportIcon: "🏸",
    date: "2025-05-18",
    venueId: "v1",
    venueName: "Cebu Sports Complex",
    format: "single_elimination",
    status: "done",
    progress: 100,
    divisionCount: 3,
    playerCount: 28,
    createdAt: "",
  },
];

export const MOCK_PLAYERS: Player[] = [
  {
    id: "1",
    organizationId: "org1",
    name: "Juan Santos",
    initials: "JS",
    handle: "@juansantos",
    color: "#CCFF33",
    division: "Men's Doubles",
    partner: "Mark Reyes",
    wins: 4,
    losses: 1,
    status: "active",
  },
  {
    id: "2",
    organizationId: "org1",
    name: "Mark Reyes",
    initials: "MR",
    handle: "@markreyes",
    color: "#3B82F6",
    division: "Men's Doubles",
    partner: "Juan Santos",
    wins: 4,
    losses: 1,
    status: "active",
  },
  {
    id: "3",
    organizationId: "org1",
    name: "Luis Cruz",
    initials: "LC",
    handle: "@luiscruz",
    color: "#F59E0B",
    division: "Men's Doubles",
    partner: "Ryan Uy",
    wins: 3,
    losses: 2,
    status: "live",
  },
  {
    id: "4",
    organizationId: "org1",
    name: "Ana Lim",
    initials: "AL",
    handle: "@analim",
    color: "#EF4444",
    division: "Mixed Doubles",
    partner: "Ryan Go",
    wins: 2,
    losses: 0,
    status: "live",
  },
  {
    id: "5",
    organizationId: "org1",
    name: "Rico Bautista",
    initials: "RB",
    handle: "@ricob",
    color: "#52525B",
    division: "Men's Singles",
    partner: "—",
    wins: 1,
    losses: 1,
    status: "upcoming",
  },
  {
    id: "6",
    organizationId: "org1",
    name: "Mae Tan",
    initials: "MT",
    handle: "@maetan",
    color: "#A855F7",
    division: "Women's Doubles",
    partner: "Ria Go",
    wins: 3,
    losses: 0,
    status: "active",
  },
  {
    id: "7",
    organizationId: "org1",
    name: "Ryan Go",
    initials: "RG",
    handle: "@ryango",
    color: "#22C55E",
    division: "Mixed Doubles",
    partner: "Ana Lim",
    wins: 2,
    losses: 0,
    status: "live",
  },
];

export const MOCK_COURTS: Court[] = [
  {
    id: "c1",
    venueId: "v1",
    venueName: "Cebu Sports Complex",
    number: 1,
    status: "occupied",
    currentMatch: "Santos/Reyes vs Cruz/Uy",
  },
  {
    id: "c2",
    venueId: "v1",
    venueName: "Cebu Sports Complex",
    number: 2,
    status: "occupied",
    currentMatch: "Go/Tan vs Lim/Flores",
  },
  {
    id: "c3",
    venueId: "v1",
    venueName: "Cebu Sports Complex",
    number: 3,
    status: "free",
  },
  {
    id: "c4",
    venueId: "v1",
    venueName: "Cebu Sports Complex",
    number: 4,
    status: "free",
  },
  {
    id: "c5",
    venueId: "v1",
    venueName: "Cebu Sports Complex",
    number: 5,
    status: "free",
  },
];

export const MOCK_ROLES: Role[] = [
  {
    id: "r1",
    organizationId: "org1",
    name: "Owner",
    abbr: "O",
    color: "#CCFF33",
    isSystem: true,
    memberCount: 1,
    permissions: [
      "org:edit",
      "member:manage",
      "role:manage",
      "tournament:create",
      "tournament:manage",
      "division:manage",
      "match:call",
      "match:score",
      "match:manage",
      "venue:manage",
    ],
  },
  {
    id: "r2",
    organizationId: "org1",
    name: "Umpire",
    abbr: "U",
    color: "#3B82F6",
    isSystem: false,
    memberCount: 3,
    permissions: ["match:call", "match:score", "match:manage"],
  },
  {
    id: "r3",
    organizationId: "org1",
    name: "Tournament Admin",
    abbr: "T",
    color: "#F59E0B",
    isSystem: false,
    memberCount: 1,
    permissions: ["tournament:create", "tournament:manage", "division:manage"],
  },
  {
    id: "r4",
    organizationId: "org1",
    name: "Scorekeeper",
    abbr: "S",
    color: "#52525B",
    isSystem: false,
    memberCount: 5,
    permissions: ["match:score"],
  },
];

export const MOCK_LIVE_MATCHES: Match[] = [
  {
    id: "m1",
    tournamentId: "1",
    divisionId: "d1",
    divisionName: "Men's Doubles – Open",
    courtId: "c1",
    courtNumber: 1,
    status: "live",
    round: "Semifinal",
    teamA: "Santos / Reyes",
    teamB: "Cruz / Uy",
    scoreA: 18,
    scoreB: 14,
    sets: [{ setNumber: 1, scoreA: 21, scoreB: 17, winner: "a" }],
  },
  {
    id: "m2",
    tournamentId: "1",
    divisionId: "d3",
    divisionName: "Mixed Doubles",
    courtId: "c2",
    courtNumber: 2,
    status: "live",
    round: "Quarterfinal",
    teamA: "Go / Tan",
    teamB: "Lim / Flores",
    scoreA: 9,
    scoreB: 12,
    sets: [],
  },
];

export const MOCK_UPCOMING: UpcomingMatch[] = [
  {
    id: "u1",
    players: "Dela Cruz vs Bautista",
    division: "Men's Singles",
    court: 3,
    time: "10:30",
  },
  {
    id: "u2",
    players: "Perez/Ong vs Dizon/Vidal",
    division: "Women's Doubles",
    court: 1,
    time: "11:00",
  },
  {
    id: "u3",
    players: "Niño/Torres vs Sy/Lao",
    division: "Men's Doubles",
    court: 2,
    time: "11:30",
  },
  {
    id: "u4",
    players: "Ramos vs Velarde",
    division: "Men's Singles",
    court: 4,
    time: "12:00",
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: "a1",
    color: "#CCFF33",
    message: "Santos/Reyes won Set 1 21–17 vs Cruz/Uy",
    time: "2 min ago",
  },
  {
    id: "a2",
    color: "#3B82F6",
    message: "New player Mark Lim registered in Mixed Doubles",
    time: "18 min ago",
  },
  {
    id: "a3",
    color: "#F59E0B",
    message: "Bracket generated for Men's Doubles – Open",
    time: "1 hr ago",
  },
  {
    id: "a4",
    color: "#52525B",
    message: "Tournament Sunday League #8 created",
    time: "2 hrs ago",
  },
];

export const ALL_PERMISSIONS = [
  "org:edit",
  "member:manage",
  "role:manage",
  "tournament:create",
  "tournament:manage",
  "division:manage",
  "match:call",
  "match:score",
  "match:manage",
  "venue:manage",
] as const;
